apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-voting-app
    name: voting-app-deploy
  name: voting-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-voting-app
      name: voting-app-pod
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: voting-app-pod
    spec:
      containers:
      - image: kodekloud/examplevotingapp_vote:v1
        name: voting-app-container
        ports:
          - containerPort: 80
        resources: {}
status: {}
