apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-voting-app
    name: redis-deploy
  name: redis-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-voting-app
      name: redis-pod
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: redis-pod
    spec:
      containers:
      - image: redis
        name: redis
        ports:
          - containerPort: 6379
        resources: {}
status: {}
