apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-voting-app
    name: result-app-deploy
  name: result-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-voting-app
      name: result-app-pod
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: result-app-pod
    spec:
      containers:
      - image: kodekloud/examplevotingapp_result:v1
        name: result-app-container
        ports:
          - containerPort: 80
        resources: {}
status: {}
