apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-voting-app
    name: postgres-deploy
  name: postgres-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-voting-app
      name: postgres-pod
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: postgres-pod
    spec:
      containers:
      - image: postgres
        name: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
        resources: {}
status: {}
