apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-svc
    app: demo-voting-app
  name: redis
spec:
  ports:
  - name: default
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis-pod
    app: demo-voting-app
  type: ClusterIP
status:
  loadBalancer: {}
