apiVersion: v1
kind: Service
metadata:
  labels:
    name: voting-svc
    app: demo-voting-app
  name: voting-svc
spec:
  ports:
  - name: 80-80
    nodePort: 30004
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: voting-app-pod
    app: demo-voting-app
  type: NodePort
status:
  loadBalancer: {}
