apiVersion: v1
kind: Pod
metadata:
  labels:
    name: result-app-pod
    app: demo-voting-app
  name: result-app-pod
spec:
  containers:
  - image: kodekloud/examplevotingapp_result:v1
    name: result-app
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
