apiVersion: v1
kind: Pod
metadata:
  labels:
    name: voting-app-pod
    app: demo-voting-app
  name: voting-app-pod
spec:
  containers:
  - image: kodekloud/examplevotingapp_vote:v1
    name: voting-app
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}